version: "3.9"
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seatdrops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: ./backend
    environment:
      DB_PASSWORD: password
      DB_USER: user
      DB_HOST: postgres
      DB_NAME: seatdrops
    depends_on:
      - postgres
    ports:
      - "5000:5000"

volumes:
  pgdata: